version: "3"
services:
  browserless-chrome:
    image: ghcr.io/browserless/chrome:latest
    restart: always
    container_name: browserless
    ports:
      - "3010:3000"
  squid:
    image: ubuntu/squid
    restart: always
    container_name: squid
    hostname: squid
    volumes:
      - ./config/squid.conf:/etc/squid/squid.conf
    ports:
      - "3218:3128"
