name: Continuous Deployment
on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: [self-hosted, pi]
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Run and Build
        run: docker compose up -d --build
